# Config file for the acts_as_solr plugin.
#
# If you change the host or port number here, make sure you update 
# them in your Solr config file

development:
  url: http://0.0.0.0:8982/solr
  jvm_options: -server -Xmx128M -Xms16M
  timeout: 0
  
production:
  url: http://127.0.0.1:8983/solr
  jvm_options: -server -Xmx192M -Xms64M
  timeout: 0

test: &TEST
  url: http://0.0.0.0:8981/solr
  jvm_options: -server -Xmx128M -Xms16M
  timeout: 0

cucumber:
  <<: *TEST
